demo/urls.py
import django

from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth
from viewflow.flow import views as viewflow

from .helloworld.flows import HelloWorldFlow
from .shipment.flows import ShipmentFlow
from .customnode.flows import DynamicSplitFlow


if django.VERSION < (1, 7):
    admin.autodiscover()

flows = {
    'helloworld': HelloWorldFlow,
    'shipment': ShipmentFlow,
    'split': DynamicSplitFlow
}


urlpatterns = [
    url(r'^$', viewflow.AllProcessListView.as_view(ns_map=flows), name="index"),
    url(r'^tasks/$', viewflow.AllTaskListView.as_view(ns_map=flows), name="tasks"),
    url(r'^queue/$', viewflow.AllQueueListView.as_view(ns_map=flows), name="queue"),

    url(r'^helloworld/', include('demo.helloworld.urls', namespace='helloworld')),
    url(r'^shipment/', include('demo.shipment.urls', namespace='shipment')),
    url(r'^split/', include('demo.customnode.urls', namespace='split')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', auth.login, name='login'),
    url(r'^accounts/logout/$', auth.logout, name='logout'),
    url(r'^', include('demo.website')),
]

viewflow/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.template import Template, Context

from .activation import STATUS
from .exceptions import FlowRuntimeError
from .fields import FlowReferenceField, TaskReferenceField, TokenField
from .managers import ProcessManager, TaskManager, coerce_to_related_instance


class AbstractProcess(models.Model):
    """
    Base class for Process data object
    """
    flow_class = FlowReferenceField()
    status = models.CharField(max_length=50, default=STATUS.NEW)

    created = models.DateTimeField(auto_now_add=True)
    finished = models.DateTimeField(blank=True, null=True)

    objects = ProcessManager()

    @property
    def created_by(self):
        return self.flow_class.task_class._default_manager \
            .get(process=self, flow_task_type='START').owner

    def active_tasks(self):
        return self.flow_class.task_class._default_manager \
            .filter(process=self, finished__isnull=True) \
            .order_by('created')

    def get_task(self, flow_task, status=None):
        """
        Return task instance
        """
        if status is None:
            status = [STATUS.NEW, STATUS.ASSIGNED, STATUS.STARTED]
        elif not isinstance(status, (list, tuple)):
            status = [status]

        return self.flow_class.task_class._default_manager.get(
            process=self, flow_task=flow_task, status__in=status)

    def summary(self):
        """
        Quick textual process state representation for end user
        """
        if self.flow_class and self.flow_class.process_class == type(self):
            return Template(self.flow_class.summary_template).render(Context({'process': self, 'flow_class': self.flow_class}))

        return "{} - {}".format(self.flow_class.process_title, self.status)

    def __str__(self):
        if self.flow_class:
            return '{} #{}'.format(self.flow_class.process_title, self.pk)
        return "<Process {}> - {}".format(self.pk, self.status)

    def refresh_from_db(self, using=None, fields=None, **kwargs):
        if hasattr(models.Model, 'refresh_from_db'):
            super(AbstractProcess, self).refresh_from_db(using=using, fields=fields, **kwargs)
        else:
            """
            django 1.6, only basic fallback
            """
            db_instance = self.__class__._default_manager.filter(pk=self.pk).get()
            for field in self._meta.concrete_fields:
                setattr(self, field.attname, getattr(db_instance, field.attname))

    class Meta:
        abstract = True


class AbstractTask(models.Model):
    """
    Base class for Task state objects.

    In addition, you have to define at least process foreign key field::

        process = models.ForeignKey(Process)

    """
    flow_task = TaskReferenceField()
    flow_task_type = models.CharField(max_length=50)
    status = models.CharField(max_length=50, default=STATUS.NEW, db_index=True)

    created = models.DateTimeField(auto_now_add=True)
    started = models.DateTimeField(blank=True, null=True)
    finished = models.DateTimeField(blank=True, null=True)
    previous = models.ManyToManyField('self', symmetrical=False, related_name='leading')
    token = TokenField(default='start')

    objects = TaskManager()

    @property
    def flow_process(self):
        """
        Returns process instance of flow_class type
        """
        if self.flow_task is not None:
            return coerce_to_related_instance(self.process, self.flow_task.flow_class.process_class)

    def summary(self):
        """
        Quick textual task result representation for end user
        """
        if self.flow_task:
            if self.finished:
                if hasattr(self.flow_task, 'task_result_summary'):
                    return Template(self.flow_task.task_result_summary or "").render(Context({
                        'process': self.flow_process,
                        'task': self,
                        'flow_class': self.flow_task.flow_class,
                        'flow_task': self.flow_task}))
            else:
                if hasattr(self.flow_task, 'task_description'):
                    return self.flow_task.task_description or ""

        return ""

    def save(self, *args, **kwargs):
        if self.status == STATUS.PREPARED:
            raise FlowRuntimeError("Can't save task with intermediate status - PREPARED")

        if self.flow_task:
            self.flow_task_type = self.flow_task.task_type

        super(AbstractTask, self).save(*args, **kwargs)

    def activate(self):
        """
        Instantiate and configure new task activation
        """
        activation = self.flow_task.activation_class()
        activation.initialize(self.flow_task, self)
        return activation

    def __str__(self):
        if self.flow_task:
            return "<{}.{}/{}> - {}".format(
                self.flow_task.flow_class._meta.flow_label,
                self.flow_task,
                self.pk,
                self.status)
        return "<Task {}> - {}".format(self.pk, self.status)

    def refresh_from_db(self, using=None, fields=None, **kwargs):
        if hasattr(models.Model, 'refresh_from_db'):
            super(AbstractTask, self).refresh_from_db(using=using, fields=fields, **kwargs)
        else:
            """
            django 1.6, only basic fallback
            """
            db_instance = self.__class__._default_manager.filter(pk=self.pk).get()
            for field in self._meta.concrete_fields:
                setattr(self, field.attname, getattr(db_instance, field.attname))

    class Meta:
        abstract = True


class Process(AbstractProcess):
    class Meta:
        verbose_name_plural = 'Process list'


class Task(AbstractTask):
    process = models.ForeignKey(Process)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, db_index=True)
    external_task_id = models.CharField(max_length=50, blank=True, null=True, db_index=True)
    owner_permission = models.CharField(max_length=255, blank=True, null=True)

    comments = models.TextField(blank=True, null=True)

viewflow/flow/views/actions.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.utils.http import is_safe_url
from django.utils.decorators import method_decorator
from django.utils.timezone import now
from django.views import generic
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _

from ...activation import STATUS
from ...decorators import flow_view
from ...exceptions import FlowRuntimeError
from .mixins import (
    FlowManagePermissionMixin, FlowTaskManagePermissionMixin,
    MessageUserMixin
)


class BaseTaskActionView(MessageUserMixin, generic.TemplateView):
    action_name = None

    def can_proceed(self):
        raise NotImplementedError

    def perform(self):
        raise NotImplementedError

    def get_template_names(self):
        flow_task = self.activation.flow_task
        opts = self.activation.flow_task.flow_class._meta

        return (
            '{}/{}/{}_{}.html'.format(opts.app_label, opts.flow_label, flow_task.name, self.action_name),
            '{}/{}/task_{}.html'.format(opts.app_label, opts.flow_label, self.action_name),
            'viewflow/flow/task_{}.html'.format(self.action_name),
            'viewflow/flow/task_action.html')

    def get_success_url(self):
        return self.activation.flow_task.get_task_url(
            self.activation.task, 'detail', user=self.request.user,
            namespace=self.request.resolver_match.namespace)

    def get_context_data(self, **kwargs):
        context = super(BaseTaskActionView, self).get_context_data(**kwargs)
        context['activation'] = self.activation
        context['flow_class'] = self.flow_class
        return context

    def post(self, request, *args, **kwargs):
        if 'run_action' in request.POST:
            self.perform()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.get(request, *args, **kwargs)

    @method_decorator(flow_view)
    def dispatch(self, request, **kwargs):
        self.activation = request.activation
        self.flow_class = self.activation.flow_class

        if not self.can_proceed():
            self.error("Task {task} Can't execute action {action}.", action=self.action_name.title)

            return redirect(self.activation.flow_task.get_task_url(
                self.activation.task, url_type='detail', user=request.user))

        return super(BaseTaskActionView, self).dispatch(request, **kwargs)


class UndoTaskView(FlowTaskManagePermissionMixin, BaseTaskActionView):
    action_name = 'undo'

    def can_proceed(self):
        return self.activation.undo.can_proceed()

    def perform(self):
        self.activation.undo()
        self.success('Task {task} has been undone.')


class CancelTaskView(FlowTaskManagePermissionMixin, BaseTaskActionView):
    action_name = 'cancel'

    def can_proceed(self):
        return self.activation.cancel.can_proceed()

    def perform(self):
        self.activation.cancel()
        self.success('Task {task} has been canceled.')


class PerformTaskView(FlowTaskManagePermissionMixin, BaseTaskActionView):
    """Non-interactive task that cancelled and need to be started manually."""

    action_name = 'execute'

    def can_proceed(self):
        return self.activation.perform.can_proceed()

    def perform(self):
        self.activation.perform()
        self.error('Task {task} has been executed.')


class ActivateNextTaskView(FlowTaskManagePermissionMixin, BaseTaskActionView):
    """Activate next task without interactive task redone."""

    action_name = 'activate_next'

    def can_proceed(self):
        return self.activation.activate_next.can_proceed()

    def perform(self):
        self.activation.activate_next()


class CancelProcessView(FlowManagePermissionMixin, generic.DetailView):
    context_object_name = 'process'
    pk_url_kwarg = 'process_pk'

    def report(self, message, level=messages.INFO, fail_silently=True, **kwargs):
        namespace = self.request.resolver_match.namespace

        process_url = reverse('{}:detail'.format(namespace), args=[self.object.pk])
        process_link = '<a href="{process_url}">#{process_pk}</a>'.format(
            process_url=process_url,
            process_pk=self.object.pk)
        kwargs.update({
            'process': process_link,
        })
        message = mark_safe(_(message).format(**kwargs))

        messages.add_message(self.request, level, message, fail_silently=fail_silently)

    def success(self, message, fail_silently=True, **kwargs):
        self.report(message, level=messages.SUCCESS, fail_silently=fail_silently, **kwargs)

    def error(self, message, fail_silently=True, **kwargs):
        self.report(message, level=messages.ERROR, fail_silently=fail_silently, **kwargs)

    def get_template_names(self):
        opts = self.flow_class._meta

        return (
            '{}/{}/process_cancel.html'.format(opts.app_label, opts.flow_label),
            'viewflow/flow/process_cancel.html')

    def get_queryset(self):
        return self.flow_class.process_class._default_manager.all()

    def get_success_url(self):
        if 'back' in self.request.GET:
            back_url = self.request.GET['back']
            if not is_safe_url(url=back_url, host=self.request.get_host()):
                back_url = '/'
            return back_url

        return reverse('{}:index'.format(self.request.resolver_match.namespace))

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        if self.object.status in [STATUS.DONE, STATUS.CANCELED]:
            self.error('Process {process} can not be canceled.')
            return HttpResponseRedirect(self.get_success_url())
        elif '_cancel_process' in request.POST:
            self._cancel_active_tasks()
            self._cancel_process()
            self.success('Process {process} has been canceled.')
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.get(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        self.flow_class = kwargs['flow_class']

        lock = self.flow_class.lock_impl(self.flow_class.instance)
        with lock(self.flow_class, kwargs['process_pk']):
            return super(CancelProcessView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CancelProcessView, self).get_context_data(**kwargs)
        context['active_tasks'] = self._get_task_list()
        context['flow_class'] = self.flow_class
        context['uncancelable_tasks'] = self._get_uncancelable_tasks(context['active_tasks'])
        return context

    def _get_task_list(self):
        active_tasks = self.object.task_set.exclude(status__in=[STATUS.DONE, STATUS.CANCELED])
        return active_tasks

    def _get_uncancelable_tasks(self, tasks):
        uncancelable = []

        for task in tasks:
            activation = task.activate()
            can_cancel = hasattr(activation, 'cancel') and activation.cancel.can_proceed()
            can_undo = hasattr(activation, 'undo') and activation.undo.can_proceed()

            if not can_undo and not can_cancel:
                uncancelable.append(task)

        return uncancelable

    def _cancel_active_tasks(self):
        active_tasks = self._get_task_list()
        for task in active_tasks:
            activation = task.activate()
            can_cancel = hasattr(activation, 'cancel') and activation.cancel.can_proceed()
            can_undo = hasattr(activation, 'undo') and activation.undo.can_proceed()

            if not can_cancel and can_undo:
                activation.undo()
                activation.cancel()
            elif can_cancel:
                activation.cancel()
            else:
                raise FlowRuntimeError("Can't cancel {}".format(task))

    def _cancel_process(self):
        self.object.status = STATUS.CANCELED
        self.object.finished = now()
        self.object.save()

viewflow/flow/views/detail.py
from django.views import generic
from django.utils.decorators import method_decorator
from django.core.exceptions import PermissionDenied
from .mixins import FlowViewPermissionMixin

from ...decorators import flow_view


class DetailTaskView(generic.TemplateView):
    """
    Default detail view for flow task.

    Get confirmation from user, assigns task and redirects to task pages.
    """

    def get_template_names(self):
        flow_task = self.activation.flow_task
        opts = self.activation.flow_task.flow_class._meta

        return (
            '{}/{}/{}_detail.html'.format(opts.app_label, opts.flow_label, flow_task.name),
            '{}/{}/task_detail.html'.format(opts.app_label, opts.flow_label),
            'viewflow/flow/task_detail.html')

    def get_context_data(self, **kwargs):
        context = super(DetailTaskView, self).get_context_data(**kwargs)
        context['activation'] = self.activation
        return context

    @method_decorator(flow_view)
    def dispatch(self, request, *args, **kwargs):
        self.activation = request.activation

        if not self.activation.flow_task.can_view(request.user, self.activation.task):
            raise PermissionDenied
        return super(DetailTaskView, self).dispatch(request, *args, **kwargs)


class DetailProcessView(FlowViewPermissionMixin, generic.DetailView):

    """Detail for process."""

    context_object_name = 'process'
    pk_url_kwarg = 'process_pk'

    def get_template_names(self):
        opts = self.flow_class._meta

        return (
            '{}/{}/process_detail.html'.format(opts.app_label, opts.flow_label),
            'viewflow/flow/process_detail.html')

    def get_context_data(self, **kwargs):
        context = super(DetailProcessView, self).get_context_data(**kwargs)
        context['task_list'] = context['process'].task_set.all().order_by('created')
        return context

    def get_queryset(self):
        return self.flow_class.process_class._default_manager.all()

viewflow/templates/viewflow/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Viewflow{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
      <div class="container">
          {% block content %}
          {% endblock %}
      </div>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
</html>

viewflow/templates/viewflow/site_index.html
{% extends 'viewflow/base.html' %}
{% load viewflow %}

{% block title %}{{ block.super}} | All processes{% endblock %}

{% block content %}
<div>
    <h1>All processes list</h1>
</div>
<table class="table">
    <thead>
        <th>#</th>
        <th>Process</th>
        <th>Started</th>
        <th>Finished</th>
        <th>Active Tasks</th>
    </thead>
    <tbody>
        {% for process in process_list %}
        <tr>
            <td><a href="{% flowurl process 'detail' ns=request.resolver_match.namespace ns_map=view.ns_map %}">{{ process.id }}</a></td>
            <td>{{ process.flow_class.process_title }}</td>
            <td>{{ process.created }}</td>
            <td>{{ process.finished|default:"" }}</td>
            <td>
                {% for task in process.active_tasks %}
                {% flowurl task user=request.user ns=request.resolver_match.namespace ns_map=view.ns_map as task_url %}
                {% if task_url %}
                <a href="{{ task_url }}?back={{ request.get_full_path|urlencode }}">
                    {{ task.flow_task }}
                </a>
                {% else %}
                    {{ task.flow_task }}
                {% endif %}
                {% endfor %}
            </td>

        </tr>
        {% empty %}
        <tr>
            <td colspan="3">No process yet</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

viewflow/templates/viewflow/site_queue.html
{% extends 'viewflow/base.html' %}
{% load viewflow %}

{% block title %}{{ block.super}} | All tasks{% endblock %}

{% block content %}
<div>
    <h1>All Queues</h1>
</div>
<table class="table">
    <thead>
        <th>#</th>
        <th>Process</th>
        <th>Name</th>
        <th class="span1">Started</th>
        <th class="span1">Finished</th>
        <th>Status</th>
    </thead>
    <tbody>
        {% for task in queue %}
        <tr>
            <td><a href="{% flowurl task user=request.user ns=request.resolver_match.namespace ns_map=view.ns_map %}">{{ task.process.id }}/{{ task.id }}</a></td>
            <td><a href="{% flowurl task.process 'detail' user=request.user ns=request.resolver_match.namespace ns_map=view.ns_map %}">{{ task.process.id }}</a></td>
            <td>{{ task.flow_task }}</td>
            <td>{{ task.created }}</td>
            <td>{{ task.finished|default:"" }}</td>
            <td>{{ task.get_status_display }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

viewflow/templates/viewflow/site_tasks.html
{% extends 'viewflow/base.html' %}
{% load viewflow %}

{% block title %}{{ block.super}} | All tasks{% endblock %}

{% block content %}
<div>
    <h1>All tasks list</h1>
</div>
<table class="table">
    <thead>
        <th>#</th>
        <th>Process</th>
        <th>Task</th>
        <th>Description</th>
        <th class="span1">Summary</th>
        <th class="span1">Assigned</th>
    </thead>
    <tbody>
        {% for task in task_list %}
        <tr>
            <td><a href="{% flowurl task user=request.user ns=request.resolver_match.namespace ns_map=view.ns_map %}">{{ task.process.id }}/{{ task.id }}</a></td>
            <td><a href="{% flowurl task.process 'detail' ns=request.resolver_match.namespace ns_map=view.ns_map %}">{{ task.flow_task.flow_class.process_title }}</a></td>
            <td>{{ task.flow_task }}</td>
            <td>{{ task.summary }}</td>
            <td>{{ task.flow_process.summary }}</td>
            <td>{{ task.created }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}