demo/shipment/urls.py
from viewflow.flow import routers
from .flows import ShipmentFlow

urlpatterns = routers.FlowRouter(ShipmentFlow).urls

demo/urls.py
import django

from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth
from viewflow.flow import views as viewflow

from .helloworld.flows import HelloWorldFlow
from .shipment.flows import ShipmentFlow
from .customnode.flows import DynamicSplitFlow


if django.VERSION < (1, 7):
    admin.autodiscover()

flows = {
    'helloworld': HelloWorldFlow,
    'shipment': ShipmentFlow,
    'split': DynamicSplitFlow
}


urlpatterns = [
    url(r'^$', viewflow.AllProcessListView.as_view(ns_map=flows), name="index"),
    url(r'^tasks/$', viewflow.AllTaskListView.as_view(ns_map=flows), name="tasks"),
    url(r'^queue/$', viewflow.AllQueueListView.as_view(ns_map=flows), name="queue"),

    url(r'^helloworld/', include('demo.helloworld.urls', namespace='helloworld')),
    url(r'^shipment/', include('demo.shipment.urls', namespace='shipment')),
    url(r'^split/', include('demo.customnode.urls', namespace='split')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', auth.login, name='login'),
    url(r'^accounts/logout/$', auth.logout, name='logout'),
    url(r'^', include('demo.website')),
]

demo/shipment/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from viewflow.models import Process, Task


class Carrier(models.Model):
    DEFAULT = 'Default'

    name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)

    def is_default(self):
        return self.name == Carrier.DEFAULT

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Insurance(models.Model):
    company_name = models.CharField(max_length=50)
    cost = models.IntegerField()

    def __str__(self):
        return '{} ${}'.format(self.company_name, self.cost)


class Shipment(models.Model):
    shipment_no = models.CharField(max_length=50)
    carrier = models.ForeignKey(Carrier, null=True)

    # customer
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.EmailField()

    # shipment addres
    address = models.CharField(max_length=150)
    city = models.CharField(max_length=150)
    state = models.CharField(max_length=150)
    zipcode = models.CharField(max_length=10)
    country = models.CharField(max_length=150)
    phone = models.CharField(max_length=50)

    # shipment data
    need_insurance = models.BooleanField(default=False)
    insurance = models.ForeignKey('Insurance', null=True)

    carrier_quote = models.IntegerField(default=0)
    post_label = models.TextField(blank=True, null=True)

    package_tag = models.CharField(max_length=50)


class ShipmentItem(models.Model):
    shipment = models.ForeignKey(Shipment)
    name = models.CharField(max_length=250)
    quantity = models.IntegerField(default=1)


class ShipmentProcess(Process):
    shipment = models.ForeignKey(Shipment, blank=True, null=True)

    def is_normal_post(self):
        try:
            if self.shipment.carrier:
                return self.shipment.carrier.is_default()
            else:
                return None
        except (Shipment.DoesNotExist, Carrier.DoesNotExist):
            return None

    def need_extra_insurance(self):
        try:
            return self.shipment.need_insurance
        except Shipment.DoesNotExist:
            return None

    class Meta:
        verbose_name_plural = 'Shipment process list'
        permissions = [
            ('can_start_request', 'Can start shipment request'),
            ('can_take_extra_insurance', 'Can take extra insurance'),
            ('can_package_goods', 'Can package goods'),
            ('can_move_package', 'Can move package')
        ]


class ShipmentTask(Task):
    class Meta:
        proxy = True

demo/shipment/views.py
from django.core.exceptions import PermissionDenied
from django.forms.models import modelform_factory, inlineformset_factory
from django.views import generic
from django.shortcuts import render, redirect
from viewflow.flow import flow_start_view
from viewflow.flow.views import FlowViewMixin, get_next_task_url


from .models import Shipment, ShipmentItem, Insurance


@flow_start_view
def start_view(request):
    form_class = modelform_factory(Shipment, fields=[
        'shipment_no', 'first_name', 'last_name',
        'email', 'phone', 'address', 'zipcode',
        'city', 'state', 'country'])

    formset_class = inlineformset_factory(Shipment, ShipmentItem, fields=[
        'name', 'quantity'], can_delete=False)

    if not request.activation.has_perm(request.user):
        raise PermissionDenied
    request.activation.prepare(request.POST or None, user=request.user)

    form = form_class(request.POST or None)
    formset = formset_class(request.POST or None)

    is_valid = all([form.is_valid(), formset.is_valid()])
    if is_valid:
        shipment = form.save()
        request.process.shipment = shipment
        for item in formset.save(commit=False):
            item.shipment = shipment
            item.save()
        request.activation.done()
        return redirect(get_next_task_url(request, request.process))

    return render(request, 'shipment/shipment/start.html', {
        'activation': request.activation,
        'form': form,
        'formset': formset
    })


class ShipmentView(FlowViewMixin, generic.UpdateView):
    def get_object(self):
        return self.activation.process.shipment


class InsuranceView(FlowViewMixin, generic.CreateView):
    model = Insurance
    fields = ['company_name', 'cost']

    def activation_done(self, form):
        shipment = self.activation.process.shipment
        shipment.insurance = self.object
        shipment.save(update_fields=['insurance'])
        self.activation.done()

viewflow/flow/views/start.py
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.views import generic
from django.utils.decorators import method_decorator

from ...decorators import flow_start_view
from .mixins import MessageUserMixin
from .utils import get_next_task_url


class BaseStartFlowMixin(object):

    """Mixin for start views, that do not implement activation interface."""

    def get_context_data(self, **kwargs):
        """Add ``activation`` to context data."""
        kwargs['activation'] = self.activation
        return super(BaseStartFlowMixin, self).get_context_data(**kwargs)

    def get_success_url(self):
        return get_next_task_url(self.request, self.activation.process)

    def get_template_names(self):
        flow_task = self.activation.flow_task
        opts = self.activation.flow_task.flow_class._meta

        return (
            '{}/{}/{}.html'.format(opts.app_label, opts.flow_label, flow_task.name),
            '{}/{}/start.html'.format(opts.app_label, opts.flow_label),
            'viewflow/flow/start.html')

    @method_decorator(flow_start_view)
    def dispatch(self, request, **kwargs):
        """Check user permissions, and prepare flow to execution."""
        self.activation = request.activation
        if not self.activation.has_perm(request.user):
            raise PermissionDenied

        self.activation.prepare(request.POST or None, user=request.user)
        return super(BaseStartFlowMixin, self).dispatch(request, **kwargs)


class StartFlowMixin(MessageUserMixin, BaseStartFlowMixin):
    def activation_done(self, *args, **kwargs):
        """Finish activation."""
        self.activation.done()
        self.success('Process {process} has been started.')

    def form_valid(self, *args, **kwargs):
        super(StartFlowMixin, self).form_valid(*args, **kwargs)
        self.activation_done(*args, **kwargs)
        return HttpResponseRedirect(self.get_success_url())


class CreateProcessView(StartFlowMixin, generic.UpdateView):
    def __init__(self, *args, **kwargs):
        super(CreateProcessView, self).__init__(*args, **kwargs)
        if self.form_class is None and self.fields is None:
            self.fields = []

    @property
    def model(self):
        return self.activation.flow_class.process_class

    def get_object(self):
        return self.activation.process

demo/shipment/templates/shipment/shipment/process_data.html
{% with process.shipment as shipment %}
<div class="row">
    <div class="col-md-4 col-lg-3">
        <div class="panel panel-default">
            <div class="panel-heading"> Shipment {{ shipment.shipment_no }}</div>
            <div class="panel-body">
                <table class="table">
                    <thead>
                        <th>Item</th>
                        <th>Count</th>
                    </thead>
                    <tbody>
                        {% for item in shipment.shipmentitem_set.all %}
                        <tr>
                            <td> {{ item.name }} </td>
                            <td> {{ item.quantity }} </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="2">No items in shipment</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-lg-2">
        <div class="panel panel-default">
            <div class="panel-heading">Address</div>
            <div class="panel-body">
                {{ shipment.zipcode }}, {{ shipment.country }}, {{ shipment.city }}, {{ shipment.state }}<br/>
                {{ shipment.address }} <br/><br/>
                <strong>Phone:</strong> {{ shipment.phone }}
            </div>
        </div>
    </div>
    <div class="col-md-2 col-xs-2">
        <div class="panel panel-default">
            <div class="panel-heading">Delivery</div>
            <div class="panel-body">
                <strong>Carrier:</strong> {{ shipment.carrier.name }}<br/>
                <strong>Insurance:</strong> {{ shipment.insurance.company_name }} {{ shipment.insurance.cost}}<br/>
            </div>
        </div>
    </div>
</div>
{% endwith %}

demo/shipment/templates/shipment/shipment/start.html
{% extends 'viewflow/flow/start.html' %}

{% block content %}
<h1>{% if activation.flow_task.task_title %}{{ activation.flow_task.task_title }}{% else %}Start {{ activation.flow_class.process_title|lower }}{% endif %}</h1>

<form role="form" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <h3>Items</h3>
    <table>
        {{ formset.as_table }}
    </table>
    {{ activation.management_form }}
    <button type="submit" name="_start" class="btn btn-primary btn-lg">Start</button>
    <button type="submit" name="_continue" class="btn btn-default btn-lg">Start and continue on this process</button>
</form>
{% endblock %}