demo/customnode/urls.py
from viewflow.flow import routers
from .flows import DynamicSplitFlow


urlpatterns = routers.FlowRouter(DynamicSplitFlow).urls

demo/helloworld/urls.py
from viewflow.flow import routers
from .flows import HelloWorldFlow

urlpatterns = routers.FlowRouter(HelloWorldFlow).urls

demo/shipment/urls.py
from viewflow.flow import routers
from .flows import ShipmentFlow

urlpatterns = routers.FlowRouter(ShipmentFlow).urls

demo/urls.py
import django

from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth
from viewflow.flow import views as viewflow

from .helloworld.flows import HelloWorldFlow
from .shipment.flows import ShipmentFlow
from .customnode.flows import DynamicSplitFlow


if django.VERSION < (1, 7):
    admin.autodiscover()

flows = {
    'helloworld': HelloWorldFlow,
    'shipment': ShipmentFlow,
    'split': DynamicSplitFlow
}


urlpatterns = [
    url(r'^$', viewflow.AllProcessListView.as_view(ns_map=flows), name="index"),
    url(r'^tasks/$', viewflow.AllTaskListView.as_view(ns_map=flows), name="tasks"),
    url(r'^queue/$', viewflow.AllQueueListView.as_view(ns_map=flows), name="queue"),

    url(r'^helloworld/', include('demo.helloworld.urls', namespace='helloworld')),
    url(r'^shipment/', include('demo.shipment.urls', namespace='shipment')),
    url(r'^split/', include('demo.customnode.urls', namespace='split')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', auth.login, name='login'),
    url(r'^accounts/logout/$', auth.logout, name='logout'),
    url(r'^', include('demo.website')),
]

demo/customnode/views.py
from django.views import generic
from django.http import HttpResponseRedirect

from viewflow.flow.views import FlowViewMixin

from . import models


class DecisionView(FlowViewMixin, generic.CreateView):
    model = models.Decision
    fields = ['decision']

    def form_valid(self, form):
        self.object = form.save(commit=False)

        self.object.user = self.request.user
        self.object.process = self.activation.process
        self.object.save()

        self.activation.done()
        self.success('Task {task} has been completed.')

        return HttpResponseRedirect(self.get_success_url())

demo/shipment/views.py
from django.core.exceptions import PermissionDenied
from django.forms.models import modelform_factory, inlineformset_factory
from django.views import generic
from django.shortcuts import render, redirect
from viewflow.flow import flow_start_view
from viewflow.flow.views import FlowViewMixin, get_next_task_url


from .models import Shipment, ShipmentItem, Insurance


@flow_start_view
def start_view(request):
    form_class = modelform_factory(Shipment, fields=[
        'shipment_no', 'first_name', 'last_name',
        'email', 'phone', 'address', 'zipcode',
        'city', 'state', 'country'])

    formset_class = inlineformset_factory(Shipment, ShipmentItem, fields=[
        'name', 'quantity'], can_delete=False)

    if not request.activation.has_perm(request.user):
        raise PermissionDenied
    request.activation.prepare(request.POST or None, user=request.user)

    form = form_class(request.POST or None)
    formset = formset_class(request.POST or None)

    is_valid = all([form.is_valid(), formset.is_valid()])
    if is_valid:
        shipment = form.save()
        request.process.shipment = shipment
        for item in formset.save(commit=False):
            item.shipment = shipment
            item.save()
        request.activation.done()
        return redirect(get_next_task_url(request, request.process))

    return render(request, 'shipment/shipment/start.html', {
        'activation': request.activation,
        'form': form,
        'formset': formset
    })


class ShipmentView(FlowViewMixin, generic.UpdateView):
    def get_object(self):
        return self.activation.process.shipment


class InsuranceView(FlowViewMixin, generic.CreateView):
    model = Insurance
    fields = ['company_name', 'cost']

    def activation_done(self, form):
        shipment = self.activation.process.shipment
        shipment.insurance = self.object
        shipment.save(update_fields=['insurance'])
        self.activation.done()

viewflow/flow/views/actions.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.utils.http import is_safe_url
from django.utils.decorators import method_decorator
from django.utils.timezone import now
from django.views import generic
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _

from ...activation import STATUS
from ...decorators import flow_view
from ...exceptions import FlowRuntimeError
from .mixins import (
    FlowManagePermissionMixin, FlowTaskManagePermissionMixin,
    MessageUserMixin
)


class BaseTaskActionView(MessageUserMixin, generic.TemplateView):
    action_name = None

    def can_proceed(self):
        raise NotImplementedError

    def perform(self):
        raise NotImplementedError

    def get_template_names(self):
        flow_task = self.activation.flow_task
        opts = self.activation.flow_task.flow_class._meta

        return (
            '{}/{}/{}_{}.html'.format(opts.app_label, opts.flow_label, flow_task.name, self.action_name),
            '{}/{}/task_{}.html'.format(opts.app_label, opts.flow_label, self.action_name),
            'viewflow/flow/task_{}.html'.format(self.action_name),
            'viewflow/flow/task_action.html')

    def get_success_url(self):
        return self.activation.flow_task.get_task_url(
            self.activation.task, 'detail', user=self.request.user,
            namespace=self.request.resolver_match.namespace)

    def get_context_data(self, **kwargs):
        context = super(BaseTaskActionView, self).get_context_data(**kwargs)
        context['activation'] = self.activation
        context['flow_class'] = self.flow_class
        return context

    def post(self, request, *args, **kwargs):
        if 'run_action' in request.POST:
            self.perform()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.get(request, *args, **kwargs)

    @method_decorator(flow_view)
    def dispatch(self, request, **kwargs):
        self.activation = request.activation
        self.flow_class = self.activation.flow_class

        if not self.can_proceed():
            self.error("Task {task} Can't execute action {action}.", action=self.action_name.title)

            return redirect(self.activation.flow_task.get_task_url(
                self.activation.task, url_type='detail', user=request.user))

        return super(BaseTaskActionView, self).dispatch(request, **kwargs)


class UndoTaskView(FlowTaskManagePermissionMixin, BaseTaskActionView):
    action_name = 'undo'

    def can_proceed(self):
        return self.activation.undo.can_proceed()

    def perform(self):
        self.activation.undo()
        self.success('Task {task} has been undone.')


class CancelTaskView(FlowTaskManagePermissionMixin, BaseTaskActionView):
    action_name = 'cancel'

    def can_proceed(self):
        return self.activation.cancel.can_proceed()

    def perform(self):
        self.activation.cancel()
        self.success('Task {task} has been canceled.')


class PerformTaskView(FlowTaskManagePermissionMixin, BaseTaskActionView):
    """Non-interactive task that cancelled and need to be started manually."""

    action_name = 'execute'

    def can_proceed(self):
        return self.activation.perform.can_proceed()

    def perform(self):
        self.activation.perform()
        self.error('Task {task} has been executed.')


class ActivateNextTaskView(FlowTaskManagePermissionMixin, BaseTaskActionView):
    """Activate next task without interactive task redone."""

    action_name = 'activate_next'

    def can_proceed(self):
        return self.activation.activate_next.can_proceed()

    def perform(self):
        self.activation.activate_next()


class CancelProcessView(FlowManagePermissionMixin, generic.DetailView):
    context_object_name = 'process'
    pk_url_kwarg = 'process_pk'

    def report(self, message, level=messages.INFO, fail_silently=True, **kwargs):
        namespace = self.request.resolver_match.namespace

        process_url = reverse('{}:detail'.format(namespace), args=[self.object.pk])
        process_link = '<a href="{process_url}">#{process_pk}</a>'.format(
            process_url=process_url,
            process_pk=self.object.pk)
        kwargs.update({
            'process': process_link,
        })
        message = mark_safe(_(message).format(**kwargs))

        messages.add_message(self.request, level, message, fail_silently=fail_silently)

    def success(self, message, fail_silently=True, **kwargs):
        self.report(message, level=messages.SUCCESS, fail_silently=fail_silently, **kwargs)

    def error(self, message, fail_silently=True, **kwargs):
        self.report(message, level=messages.ERROR, fail_silently=fail_silently, **kwargs)

    def get_template_names(self):
        opts = self.flow_class._meta

        return (
            '{}/{}/process_cancel.html'.format(opts.app_label, opts.flow_label),
            'viewflow/flow/process_cancel.html')

    def get_queryset(self):
        return self.flow_class.process_class._default_manager.all()

    def get_success_url(self):
        if 'back' in self.request.GET:
            back_url = self.request.GET['back']
            if not is_safe_url(url=back_url, host=self.request.get_host()):
                back_url = '/'
            return back_url

        return reverse('{}:index'.format(self.request.resolver_match.namespace))

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        if self.object.status in [STATUS.DONE, STATUS.CANCELED]:
            self.error('Process {process} can not be canceled.')
            return HttpResponseRedirect(self.get_success_url())
        elif '_cancel_process' in request.POST:
            self._cancel_active_tasks()
            self._cancel_process()
            self.success('Process {process} has been canceled.')
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.get(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        self.flow_class = kwargs['flow_class']

        lock = self.flow_class.lock_impl(self.flow_class.instance)
        with lock(self.flow_class, kwargs['process_pk']):
            return super(CancelProcessView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CancelProcessView, self).get_context_data(**kwargs)
        context['active_tasks'] = self._get_task_list()
        context['flow_class'] = self.flow_class
        context['uncancelable_tasks'] = self._get_uncancelable_tasks(context['active_tasks'])
        return context

    def _get_task_list(self):
        active_tasks = self.object.task_set.exclude(status__in=[STATUS.DONE, STATUS.CANCELED])
        return active_tasks

    def _get_uncancelable_tasks(self, tasks):
        uncancelable = []

        for task in tasks:
            activation = task.activate()
            can_cancel = hasattr(activation, 'cancel') and activation.cancel.can_proceed()
            can_undo = hasattr(activation, 'undo') and activation.undo.can_proceed()

            if not can_undo and not can_cancel:
                uncancelable.append(task)

        return uncancelable

    def _cancel_active_tasks(self):
        active_tasks = self._get_task_list()
        for task in active_tasks:
            activation = task.activate()
            can_cancel = hasattr(activation, 'cancel') and activation.cancel.can_proceed()
            can_undo = hasattr(activation, 'undo') and activation.undo.can_proceed()

            if not can_cancel and can_undo:
                activation.undo()
                activation.cancel()
            elif can_cancel:
                activation.cancel()
            else:
                raise FlowRuntimeError("Can't cancel {}".format(task))

    def _cancel_process(self):
        self.object.status = STATUS.CANCELED
        self.object.finished = now()
        self.object.save()

viewflow/flow/views/detail.py
from django.views import generic
from django.utils.decorators import method_decorator
from django.core.exceptions import PermissionDenied
from .mixins import FlowViewPermissionMixin

from ...decorators import flow_view


class DetailTaskView(generic.TemplateView):
    """
    Default detail view for flow task.

    Get confirmation from user, assigns task and redirects to task pages.
    """

    def get_template_names(self):
        flow_task = self.activation.flow_task
        opts = self.activation.flow_task.flow_class._meta

        return (
            '{}/{}/{}_detail.html'.format(opts.app_label, opts.flow_label, flow_task.name),
            '{}/{}/task_detail.html'.format(opts.app_label, opts.flow_label),
            'viewflow/flow/task_detail.html')

    def get_context_data(self, **kwargs):
        context = super(DetailTaskView, self).get_context_data(**kwargs)
        context['activation'] = self.activation
        return context

    @method_decorator(flow_view)
    def dispatch(self, request, *args, **kwargs):
        self.activation = request.activation

        if not self.activation.flow_task.can_view(request.user, self.activation.task):
            raise PermissionDenied
        return super(DetailTaskView, self).dispatch(request, *args, **kwargs)


class DetailProcessView(FlowViewPermissionMixin, generic.DetailView):

    """Detail for process."""

    context_object_name = 'process'
    pk_url_kwarg = 'process_pk'

    def get_template_names(self):
        opts = self.flow_class._meta

        return (
            '{}/{}/process_detail.html'.format(opts.app_label, opts.flow_label),
            'viewflow/flow/process_detail.html')

    def get_context_data(self, **kwargs):
        context = super(DetailProcessView, self).get_context_data(**kwargs)
        context['task_list'] = context['process'].task_set.all().order_by('created')
        return context

    def get_queryset(self):
        return self.flow_class.process_class._default_manager.all()

viewflow/flow/views/mixins.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.core.urlresolvers import reverse
from django.utils.decorators import method_decorator
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _


class LoginRequiredMixin(object):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)


class FlowViewPermissionMixin(object):
    """
    Mixin for flow views, check the view permission.
    """
    def dispatch(self, *args, **kwargs):
        self.flow_class = kwargs['flow_class']
        return permission_required(self.flow_class.instance.view_permission_name)(
            super(FlowViewPermissionMixin, self).dispatch)(*args, **kwargs)


class FlowManagePermissionMixin(object):
    """
    Mixin for flow flow views, check flow manage permission.
    """
    def dispatch(self, *args, **kwargs):
        self.flow_class = kwargs['flow_class']
        return permission_required(self.flow_class.instance.manage_permission_name)(
            super(FlowManagePermissionMixin, self).dispatch)(*args, **kwargs)


class FlowTaskManagePermissionMixin(object):
    """
    Mixin for flow task views, check flow manage permission.
    """
    def dispatch(self, *args, **kwargs):
        self.flow_task = kwargs['flow_task']
        self.flow_class = self.flow_task.flow_class
        return permission_required(self.flow_class.instance.manage_permission_name)(
            super(FlowTaskManagePermissionMixin, self).dispatch)(*args, **kwargs)


class MessageUserMixin(object):
    def report(self, message, level=messages.INFO, fail_silently=True, **kwargs):
        namespace = self.request.resolver_match.namespace

        process_url = reverse('{}:detail'.format(namespace), args=[self.activation.process.pk])
        process_link = '<a href="{process_url}">#{process_pk}</a>'.format(
            process_url=process_url,
            process_pk=self.activation.process.pk)

        task_url = self.activation.task.flow_task.get_task_url(
            self.activation.task, url_type='detail', user=self.request.user, namespace=namespace)
        task_link = '<a href="{task_url}">#{task_pk}</a>'.format(
            task_url=task_url,
            task_pk=self.activation.task.pk)

        kwargs.update({
            'process': process_link,
            'task': task_link
        })
        message = mark_safe(_(message).format(**kwargs))

        messages.add_message(self.request, level, message, fail_silently=fail_silently)

    def success(self, message, fail_silently=True, **kwargs):
        self.report(message, level=messages.SUCCESS, fail_silently=fail_silently, **kwargs)

    def error(self, message, fail_silently=True, **kwargs):
        self.report(message, level=messages.ERROR, fail_silently=fail_silently, **kwargs)


class FlowListMixin(object):
    """
    Mixin for list view contains multiple flows
    """

    ns_map = None

    def __init__(self, *args, **kwargs):
        self.ns_map = kwargs.get('ns_map', {})
        super(FlowListMixin, self).__init__(*args, **kwargs)

    @property
    def flows(self):
        return self.ns_map.values()

demo/templates/viewflow/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Viewflow Demo{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">
    <style type="text/css">
      .glyphicon{
          min-width: 15px;
      }
    </style>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
      <nav class="navbar navbar-default" role="navigation" style="margin-bottom: 0">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#viewflow-navlinks">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a href="/" class="navbar-brand">{% block branding %}Viewflow{% endblock %}</a>
          </div>
          <div class="collapse navbar-collapse navbar-right" id="viewflow-navlinks">
              {% block navright %}
              <ul class="nav navbar-nav">
                  {% if request.user.is_anonymous %}
                  <li>
                      <a href="{% url 'login' %}">Login</a>
                  </li>
                  {% else %}
                  <li>
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ request.user|title }} <b class="caret"></b></a>
                      <ul class="dropdown-menu">
                          {% for user in users %}
                          <li><a href="{% url 'login_as' %}?user_pk={{ user.pk }}"><i class="glyphicon {% if request.user == user %}glyphicon-ok{% endif %}"></i> {{ user.username|title }}</a></li>
                          {% endfor %}
                          <li><a href="{% url 'login_as' %}"><i class="glyphicon {% if request.user.is_anonymous %}glyphicon-ok{% endif %}"></i> Logout</a></li>
                      </ul>
                  </li>
                  {% endif %}
                  {% endblock %}
          </div>
      </nav>
      <div style="width:300px;position:absolute; padding-top:2rem;">
          <div class="container-fluid">
              <div class="col-lg-12">
                  <ul class="nav nav-pills nav-stacked" id="sidenav">
                      <li><ul class="nav nav-pills nav-stacked">
                              <li><a href="{% url 'index' %}">All Process</a>
                                  <ul class="nav nav-pills nav-stacked">
                                      {% if perms.helloworld.view_helloworldprocess %}
                                      <li><a href="{% url 'helloworld:index' %}">&nbsp;&nbsp;&nbsp;&nbsp;Hello World</a></li>
                                      {% endif %}
                                      {% if perms.shipment.view_shipmentprocess %}
                                      <li><a href="{% url 'shipment:index' %}">&nbsp;&nbsp;&nbsp;&nbsp;Shipment</a></li>
                                      {% endif %}
                                      {% if perms.customnode.view_dynamicsplitprocess %}
                                      <li><a href="{% url 'split:index' %}">&nbsp;&nbsp;&nbsp;&nbsp;Dynamic split</a></li>
                                      {% endif %}
                                  </ul>
                              </li>
                              <li><a href="{% url 'tasks' %}">My tasks</a> </li>
                              <li><a href="{% url 'queue' %}">Available tasks</a> </li>
                          </ul>
                      </li>
                  </ul>
              </div>
          </div>
      </div>
      <div style="position:absolute;margin-left:300px;width:calc(100% - 300px);padding-top:0.5rem;">
          <div class="container-fluid">
              {% if messages %}
              <div class="row">
                  <div class="col-lg-8">
                      {% for message in messages %}
                      <div class="alert alert-{{ message.tags }} alert-dismissible">{{ message }}</div>
                      {% endfor %}
                  </div>
              </div>
              {% endif %}
              {% block content %}
              <h1>Hello, world!</h1>
              {% endblock %}
          </div>
      </div>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
      <script type="text/javascript">
        (function( $ ) {
          $.fn.activeNavigation = function(selector) {
            var pathname = window.location.pathname
            var hrefs = []
            $(selector).find("a").each(function() {
              if (pathname.indexOf($(this).attr("href")) > -1) 
                hrefs.push($(this))
            })
            if (hrefs.length) {
              hrefs.sort(function(a,b){
                return b.attr("href").length - a.attr("href").length
              })
              hrefs[0].closest('li').addClass("active")
            }
          };
        })(jQuery);
        $(document).activeNavigation("#sidenav");
      </script>
  </body>
</html>